export const PLATFORM_FEE_PERCENT = 8

export const TRUST_SCORE = {
  INITIAL: 100,
  MAX: 100,
  DELTAS: {
    BOOKING_COMPLETED: 2,
    BOOKING_COMPLETED_WITH_REVIEW: 1,
    LATE_CANCELLATION: -5,
    VERY_LATE_CANCELLATION: -10,
    NO_SHOW: -20,
    DISPUTE_WON: 10,
  },
  MONTHLY_RECOVERY: 1,
  TIERS: {
    EXCELLENT: 90,
    GOOD: 70,
    FAIR: 50,
    POOR: 30,
  },
} as const

export const CANCELLATION_POLICY = {
  FULL_REFUND_HOURS: 24,
  PARTIAL_REFUND_HOURS: 2,
  PARTIAL_REFUND_PERCENT: 50,
} as const

export const NO_SHOW = {
  MARK_AFTER_MINUTES: 30,
  PENALTY_FLAT_RON: 10,
  PENALTY_PERCENT: 20,
  DISPUTE_WINDOW_HOURS: 24,
} as const

export const REVIEW = {
  MIN_TEXT_LENGTH: 10,
  MAX_TEXT_LENGTH: 500,
  MAX_PHOTOS: 3,
  EDIT_WINDOW_HOURS: 24,
  SUBMIT_WINDOW_DAYS: 14,
  MIN_FOR_PUBLIC_RATING: 3,
} as const

export const BOOKING = {
  MAX_ADVANCE_DAYS_DEFAULT: 60,
  MIN_DURATION_HOURS: 1,
  MAX_DURATION_HOURS: 4,
} as const

export const SHIRT_COLOURS = [
  'RED',
  'BLUE',
  'GREEN',
  'YELLOW',
  'ORANGE',
  'WHITE',
  'BLACK',
  'PURPLE',
] as const
